'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeContextProvider, LocaleContextProvider } from '@/contexts'
import '@/styles/globals.sass'
import '@/styles/reset.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Admin',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <LocaleContextProvider>
      <ThemeContextProvider>
        <html lang='fr'>
          <body className={inter.className}>
            {children}
          </body>
        </html>
      </ThemeContextProvider>
    </LocaleContextProvider>
  )
}
